 const defaultUser = {
    avatar_url: "https://avatars.githubusercontent.com/u/67919714?v=4",
    bio: "I get a huge kick out of little things. I am curious about everything.",
    blog: "",
    company: null,
    created_at: "2020-07-06T16:46:21Z",
    email: null,
    events_url: "https://api.github.com/users/sarahdherren/events{/privacy}",
    followers: 3,
    followers_url: "https://api.github.com/users/sarahdherren/followers",
    following: 5,
    following_url: "https://api.github.com/users/sarahdherren/following{/other_user}",
    gists_url: "https://api.github.com/users/sarahdherren/gists{/gist_id}",
    gravatar_id: "",
    hireable: null,
    html_url: "https://github.com/sarahdherren",
    id: 67919714,
    location: "New Orleans",
    login: "sarahdherren",
    name: "Sarah D Herren",
    node_id: "MDQ6VXNlcjY3OTE5NzE0",
    organizations_url: "https://api.github.com/users/sarahdherren/orgs",
    public_gists: 0,
    public_repos: 45,
    received_events_url: "https://api.github.com/users/sarahdherren/received_events",
    repos_url: "https://api.github.com/users/sarahdherren/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/sarahdherren/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sarahdherren/subscriptions",
    twitter_username: "sarahdherren",
    type: "User",
    updated_at: "2021-07-08T01:50:07Z",
    url: "https://api.github.com/users/sarahdherren"
};